//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrestComplaintManagement.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyMember
    {
        public int PropertyMemberId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Gendar { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> ParentMemberId { get; set; }
        public Nullable<int> ResidentTypeId { get; set; }
        public Nullable<int> RelationshipTypeId { get; set; }
        public string AlternateContactNumber { get; set; }
        public string ProfileimageUrl { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovalComments { get; set; }
        public Nullable<bool> IsResiding { get; set; }
        public string AccessKey { get; set; }
        public Nullable<bool> IsDeactivated { get; set; }
        public Nullable<System.DateTime> DeactivatedOn { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<int> PrimaryOwnerId { get; set; }
        public Nullable<bool> IsOwner { get; set; }
    
        public virtual PropertyMember PropertyMember1 { get; set; }
        public virtual PropertyMember PropertyMember2 { get; set; }
        public virtual PropertyMember PropertyMember11 { get; set; }
        public virtual PropertyMember PropertyMember3 { get; set; }
    }
}
